SET PRJDRV=V
IF EXIST %PRJDRV%:\%~NX0 GOTO FINISH

%~D0
CD "%~DP0"

SUBST %PRJDRV%: /D
SUBST %PRJDRV%: .
IF ERRORLEVEL 1 PAUSE

:FINISH
%PRJDRV%:
CD %PRJDRV%:\
"%COMMANDER_EXE%" /O /S "%PRJDRV%:\"
